server:
  port: 8080

spring:
  application:
    name: shortlink-server
  datasource:
    url: jdbc:mysql://localhost:3306/shortlink?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379

mybatis:
  configuration:
    map-underscore-to-camel-case: true

shortlink:
  cache:
    # 正常短链缓存TTL（秒），小于等于0表示禁用正常短链缓存。
    code-ttl-seconds: 1800
    # 空值缓存TTL（秒），小于等于0表示禁用空值缓存。
    null-ttl-seconds: 120
